name: Run AWS Glue Job on Push

on:
  push:
    branches:
      - main  # Change this to your working branch if needed

jobs:
  deploy-glue-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1  

    - name: Start AWS Glue Job
      run: |
        aws glue start-job-run --job-name yelp-glue-etl
